### PR TITLE
feat(gitlab): Add `email` to `gitlab_group_members`

### LINKED ISSUE #10117: [FR] gitlab: need `email` in `gitlab_group_members`
### Which problem is this feature request solving?

Hi,

I think there's no email field.

Please add email field.

And also please take care of gitlab api.

### Describe the solution you'd like

I can see email in official docs.
Please refer to https://docs.gitlab.com/ee/api/members.html.

### Pull request (optional)

- [ ] I can submit a pull request

### PR DESCRIPTION
**Pull request by candiduslynx**
Closes #10117

Library update is required due to https://github.com/xanzy/go-gitlab/pull/1702 present only there

BEGIN_COMMIT_OVERRIDE
feat(gitlab): Add `email` to `gitlab_group_members` (#10139)

feat(gitlab): Add `ip_restriction_ranges` to `gitlab_groups` (#10139)

feat(gitlab): Add `_links` to `gitlab_projects_releases` (#10139)

feat(gitlab): Update `gitlab_projects` resource (#10139)
END_COMMIT_OVERRIDE

### CODE REVIEW

**Review by bbernays — COMMENTED** [review]
Shouldn't this PR just be an dependency bump?

**Comment by candiduslynx** [comment]
Well, it was a requested feature https://github.com/cloudquery/cloudquery/issues/10117

**Comment by erezrokah** [comment]
I manually triggered the dep update https://github.com/cloudquery/cloudquery/pull/10145.
It had no breaking changes so it got auto merged.

**Comment by candiduslynx** [comment]
Closing as #10145 got merged

**Pull request closed without merging**
