### PR TITLE
feat(datadog): Migrate codegen to transformations

### PR DESCRIPTION
**Pull request by yevgenypats**

### CODE REVIEW

**Comment by hermanschaaf** [comment]
@yevgenypats I think this PR included changes to the crowdstrike plugin by accident as well

**Comment by disq** [comment]
`AdditionalProperties` was always skipped in codegen, maybe do it here as well?

**Comment by yevgenypats** [comment]
> `AdditionalProperties` was always skipped in codegen, maybe do it here as well?

why was it skipped though?

**Comment by disq** [comment]
> > `AdditionalProperties` was always skipped in codegen, maybe do it here as well?
> 
> why was it skipped though?

Not sure but it looks like an empty, undocumented map.

**Review by hermanschaaf — APPROVED** [review]

**Pull request merged**
