### PR TITLE
feat(website): Add Firestore

### PR DESCRIPTION
**Pull request by erezrokah**
#### Summary

Follow up to https://github.com/cloudquery/cloudquery/pull/9653. I'll need some help to confirm the docs, cc @BubbaJoe 

Docs in https://cloudquery-oo1n5e8ec-cloudquery.vercel.app/docs/plugins/sources/firestore/overview

### CODE REVIEW

**Comment by BubbaJoe** [comment]
Thanks, this already looks really well done! Can you add docs for the following fields?

MaxBatchSize - when testing extract millions of rows. If the request took longer than a minute the batch would timeout. So I set the default to 50,000 IIRC. This might need to be configured depending on bandwidth + cpu.

Also OrderByField - this is optional but you can get your results ordered by a specific fields (yes, this can be more than 1, maybe I should have made it plural) of course this requires you to add an index on firebase which can only be done on the UI right now.


OrderByDirection - not used unless the above is field is specified but I think this is self explanatory.

**Comment by BubbaJoe** [comment]
@erezrokah Forgot to tag you here ^

**Comment by erezrokah** [comment]
Thanks @BubbaJoe, that's super helpful. I followed up with https://github.com/cloudquery/cloudquery/pull/10007/commits/7f7925f9cb09645d5ccf0c4b5976d47abdd1305a and renamed those to `order_by` and `order_direction`. Do that make sense?

Also it seems the spec values were not used so I fixed that, see https://github.com/cloudquery/cloudquery/pull/10007/commits/7f7925f9cb09645d5ccf0c4b5976d47abdd1305a#diff-2900389b353248fc48ac304a58d98219fa4c209abf43ccb456a43f4952db22f5R63

Please let me know if that looks OK.

**Comment by BubbaJoe** [comment]
Thanks! Looks really good!

**Review by disq — APPROVED** [review]

**Comment by erezrokah** [comment]
Officially released, thanks @BubbaJoe see https://github.com/cloudquery/cloudquery/releases/tag/plugins-source-firestore-v1.0.0

**Pull request merged**
