### PR TITLE
fix: Updated query dynamodb/autoscale_or_ondemand.sql

### PR DESCRIPTION
**Pull request by ronsh12**
Change the query to be more organized and only include the relevant rows.

### CODE REVIEW

**Review by jsonpr — CHANGES_REQUESTED** [review]
From reading this control https://docs.aws.amazon.com/securityhub/latest/userguide/dynamodb-controls.html#dynamodb-1, our logic shouldn't check for replicas and their status.  This check should cover `whether an Amazon DynamoDB table can scale its read and write capacity as needed.` and specifically `passes if the table uses either on-demand capacity mode or provisioned mode with auto scaling configured`

@ronsh12  - could you check on this, I believe we'll need additional information not contained in here: https://www.cloudquery.io/docs/plugins/sources/aws/tables/aws_dynamodb_tables.  Specifically information about the table's billing mode (Provisioned or On-Demand) and then linking that to autoscaling (https://www.cloudquery.io/docs/plugins/sources/aws/tables/aws_applicationautoscaling_policies).

**Comment by ronsh12** [comment]
> From reading this control https://docs.aws.amazon.com/securityhub/latest/userguide/dynamodb-controls.html#dynamodb-1, our logic shouldn't check for replicas and their status. This check should cover `whether an Amazon DynamoDB table can scale its read and write capacity as needed.` and specifically `passes if the table uses either on-demand capacity mode or provisioned mode with auto scaling configured`
> 
> @ronsh12 - could you check on this, I believe we'll need additional information not contained in here: https://www.cloudquery.io/docs/plugins/sources/aws/tables/aws_dynamodb_tables. Specifically information about the table's billing mode (Provisioned or On-Demand) and then linking that to autoscaling (https://www.cloudquery.io/docs/plugins/sources/aws/tables/aws_applicationautoscaling_policies).

Changed this.

**Comment by ronsh12** [comment]
in DBT changed too - 
https://github.com/cloudquery/policies-premium/pull/178

**Comment by erezrokah** [comment]
Closing as stale, please re-open if not the case

**Pull request closed without merging**
