### PR TITLE
chore(website): Add sources table fillers

### PR DESCRIPTION
**Pull request by erezrokah**
#### Summary

Fixes https://github.com/cloudquery/cloudquery/issues/3344 in a very ugly way (solution 1.)

The other option is to use renovate to do it via a regex and let it handle any conflicts

### CODE REVIEW

**Comment by yevgenypats** [comment]
Yeah, that seems to build more tech debt on top of tech debt. Maybe we can use nextra parameters instead of changing the files on each release?

**Comment by erezrokah** [comment]
> Maybe we can use nextra parameters instead of changing the files on each release?

`sources.md` needs to match https://github.com/cloudquery/cloudquery/blob/66e677727114f8764433006271aa891026b19f9f/.github/workflows/release_plugin.yml#L99

so we either keep the structure or find another (e.g. renovate) to do the updates

**Comment by yevgenypats** [comment]
> > Maybe we can use nextra parameters instead of changing the files on each release?
> 
> `sources.md` needs to match
> 
> https://github.com/cloudquery/cloudquery/blob/66e677727114f8764433006271aa891026b19f9f/.github/workflows/release_plugin.yml#L99
> 
> so we either keep the structure or find another (e.g. renovate) to do the updates

Maybe Im missing something and worth doing short live session. but can't we use ${LATEST_AWS_VERSION} in the markdown and turn it into `.mdx`?

**Review by yevgenypats — CHANGES_REQUESTED** [review]
I would like to discuss a solution without search and replace bash script. proposed here - https://github.com/cloudquery/cloudquery/pull/3451

**Comment by erezrokah** [comment]
> I would like to discuss a solution without search and replace bash script. proposed here - #3451

Cool, that should work much better 🚀  Nice one 🎸 I'll comment on that PR

**Pull request closed without merging**
