### PR TITLE
chore(ci-aws): Remove sanity sync test

### PR DESCRIPTION
**Pull request by erezrokah**
#### Summary

This sanity test was added in https://github.com/cloudquery/cloudquery/pull/5503 due to https://github.com/cloudquery/cloudquery-issues/issues/459.
However it has an increasing cost as we add more build minutes, and trying to catch SDK bugs using the AWS plugin is probably not the best approach.

> On the latest release PR this step too 27m and counting only to be killed by our build timeout, see https://github.com/cloudquery/cloudquery/actions/runs/4299344604/jobs/7494467760

### CODE REVIEW

**Review by yevgenypats — APPROVED** [review]

**Comment by hermanschaaf** [comment]
Maybe we should just not sync all tables in this test, only one or two?

**Comment by erezrokah** [comment]
> Maybe we should just not sync all tables in this test, only one or two?

I was thinking that too... Maybe just buckets? It will give us a bit of confidence. I can go either way

**Comment by hermanschaaf** [comment]
@erezrokah Yeah I think this test is useful, but let's make it quick. I think any table will do, even if there are no resources.

**Comment by bbernays** [comment]
Maybe also only sync a single region?

**Comment by erezrokah** [comment]
Replaced by https://github.com/cloudquery/cloudquery/pull/8666

**Pull request closed without merging**
