### PR TITLE
feat: Add support for ACL configuration in S3 Destination

### PR DESCRIPTION
**Pull request by caiorcferreira**
#### Summary

This pull request adds ACL configuration support to the S3 destination plugin. This feature allows to specify the Access Control List (ACL) policy in the S3 destination plugin.

⚠️ **This is a contribution to a plugin, and I have read the relevant section of the [contribution guidelines](https://github.com/cloudquery/cloudquery/blob/main/CONTRIBUTING.md#open-core-vs-open-source) 🧑‍🎓 before submitting this PR** ⚠️

#### Problem Addressed

Before this PR, users could not specify an ACL policy when putting an object in an S3 bucket using the S3 destination plugin. This limitation could prevent users from sending data across AWS accounts.

### CODE REVIEW

**Comment by bbernays** [comment]
@caiorcferreira - Overall this looks good, would you mind updating it so that the spacing for the files that you updated isn't changed from tabs/spaces? This will help reduce the size of the change

**Comment by caiorcferreira** [comment]
@bbernays just fixed the spacing!

**Comment by caiorcferreira** [comment]
Hi @bbernays, could you give some help? This [job](https://github.com/cloudquery/cloudquery/actions/runs/9095706557/job/25004064437?pr=17953) failed due to an authentication error. It does not look like related to the PR.

**Comment by bbernays** [comment]
> Hi @bbernays, could you give me some help? This [job](https://github.com/cloudquery/cloudquery/actions/runs/9095706557/job/25004064437?pr=17953) failed due to an authentication error. It does not look like related to the PR.

Hi @caiorcferreira - Because the tests need access to our AWS account to test the destination against a real bucket. I am working on copying your branch to my own branch then will run the tests and once those tests pass, we will force merge your pr

**Comment by bbernays** [comment]
@caiorcferreira - Thank you for this contribution, we have kicked off the release of `v7.1.0` of the S3 destination plugin. It should be available in the CloudQuery Hub in about 20 minutes

**Pull request merged**
