### PR TITLE
chore(website): Inconsistent yml vs. yaml in markdown format, remove extra doc

### PR DESCRIPTION
**Pull request by disq**
Fix inconsistency, fix potential build failures

### CODE REVIEW

**Review by erezrokah — APPROVED** [review]

**Comment by erezrokah** [comment]
Actually doesn't this belongs under `website`?

**Comment by erezrokah** [comment]
https://github.com/cloudquery/cloudquery/tree/6452d0ed5a44abad9d7530af6e79cde6504d0c4c/website/pages/docs/plugins/sources/gandi

I think this file should be deleted

**Comment by erezrokah** [comment]
We link to the Website in the plugin's readme so no need for the `docs` dir (it's moved to the Website)

**Comment by disq** [comment]
> We link to the Website in the plugin's readme so no need for the `docs` dir (it moved to the Website)

Removed @erezrokah

**Review by erezrokah — APPROVED** [review]

**Pull request merged**
