### PR TITLE
feat(azure-resources): Add DNS Record Sets

### PR DESCRIPTION
**Pull request by yvardhineni**
#### Summary
Fixes https://github.com/cloudquery/cloudquery/issues/10847

### CODE REVIEW

**Comment by yvardhineni** [comment]
@yevgenypats @erezrokah @disq please review

**Comment by yvardhineni** [comment]
@hermanschaaf Please review

**Comment by hermanschaaf** [comment]
Hi @yvardhineni, thanks for this PR 👍 

It looks good from a first read through; we're just in the middle of a migration to plugin-sdk v3, now merged to main and due for release as part of a major new Azure version early next week (likely Monday). We'll need to update this PR to import plugin-sdk v3 rather than v2, and do any other required changes around that. 

We can help you with this, but it will probably have to wait until Monday as we're still working out some of the details.

**Comment by yvardhineni** [comment]
Thanks for the review @hermanschaaf, sure will wait till the v3 upgrade and update this PR with the necessary changes.

**Comment by yvardhineni** [comment]
@hermanschaaf @erezrokah I have updated the plugin SDK to V3, Please let me know if any other changes required

**Review by erezrokah — APPROVED** [review]
Looks great @yvardhineni, thank you for following up on this 🚀

**Pull request merged**
