### PR TITLE
chore: Streamline names

### PR DESCRIPTION
**Pull request by candiduslynx**
Follow-up for #15706

### CODE REVIEW

**Review by disq — APPROVED** [review]

**Comment by yogur** [comment]
Hey @disq @candiduslynx,

Are you aware of the target release date for releasing these changes and the ones in #15706?

**Comment by erezrokah** [comment]
Hi @yogur, this PR has no user facing changes, however #15706 was released in https://hub.cloudquery.io/plugins/source/cloudquery/aws/v23.2.0/versions?search=aws

**Comment by yogur** [comment]
Hey @erezrokah, I was looking in the [CHANGELOG.md](https://github.com/cloudquery/cloudquery/blob/main/plugins/source/aws/CHANGELOG.md) which is why I missed it. I will use the release you referenced then. Thanks!

**Pull request merged**
