### PR TITLE
chore(file): Enable JSON:SkipMigrateAppend in testing

### PR DESCRIPTION
**Pull request by disq**
filetypes update ([PR](https://github.com/cloudquery/cloudquery/pull/8218)) fails otherwise.

### CODE REVIEW

**Review by hermanschaaf — APPROVED** [review]

**Review by erezrokah — APPROVED** [review]
Looks good to unblock the PR, but let's update the title to reflect it does dep updates as the testing change is not relevant to users.

I think the "proper" fix should be to set a migrate strategy for the append tests, but I'll do that separately

**Review by candiduslynx — APPROVED** [review]

**Comment by disq** [comment]
@erezrokah Renamed as `chore`. This only applies to the file plugin that's why it's `chore(file)` and not `fix(deps)`.

**Comment by erezrokah** [comment]
> @erezrokah Renamed as `chore`. This only applies to the file plugin that's why it's `chore(file)` and not `fix(deps)`.

It updates dependencies which is a user facing change so it should be at least `fix`. For example this update includes https://github.com/cloudquery/filetypes/pull/71

**Comment by disq** [comment]
Ah sorry it wasn't meant to update dependencies. Fixing

**Comment by disq** [comment]
@erezrokah not updating dependencies any more, that will be done by the linked PR.

**Review by erezrokah — APPROVED** [review]

**Pull request merged**
