### PR TITLE
fix(gcp): Skip unusable field PrivateKeyData

### PR DESCRIPTION
**Pull request by SCKelemen**
`ServiceAccountKey` in GCP IAM contains an unused field. The `PrivateKeyData` field is only returned once, at the time of key creation. Therefore this field will always be null.

- [x] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [x] Test locally on your own infrastructure
- [x] Run `go fmt` to format your code 🖊
- [ ] Lint your changes via `golangci-lint run` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [ ] Update or add tests 🧪
- [x] Ensure the status checks below are successful ✅

### CODE REVIEW

**Comment by erezrokah** [comment]
/docs sha=42feff17179976dad84f1fe38b6d4bbd60fb7901 plugin=gcp

**Comment by erezrokah** [comment]
@SCKelemen You'll need to re-generate the code gen via `make gen-code`

**Comment by SCKelemen** [comment]
This field should always be null, as this api won't ever return anything other than null. Should dropping this column be a breaking change?

**Review by yevgenypats — APPROVED** [review]

**Comment by yevgenypats** [comment]
> This field should always be null, as this api won't ever return anything other than null. Should dropping this column be a breaking change?

dropping is not a breaking change as our auto-migrator wont drop columns by default

**Pull request merged**
