### PR TITLE
chore(github): Fix triage label in bug report issue template

### PR DESCRIPTION
**Pull request by candiduslynx**

### CODE REVIEW

**Review by erezrokah — COMMENTED** [review]
Hi @candiduslynx, can you explain what's the reason for this change?

**Comment by candiduslynx** [comment]
@erezrokah there's no [`needs-triage`](https://github.com/cloudquery/cloudquery/labels/needs-triage) label but there is [`triage required`](https://github.com/cloudquery/cloudquery/labels/triage%20required) one.

**Comment by erezrokah** [comment]
> @erezrokah there's no [`needs-triage`](https://github.com/cloudquery/cloudquery/labels/needs-triage) label but there is [`triage required`](https://github.com/cloudquery/cloudquery/labels/triage%20required) one.

I renamed the `triage required` label to `needs-triage`. Since we have only 1 issues with it I think that should do it.
Is the PR required after the rename?

**Comment by candiduslynx** [comment]
@erezrokah I'll drop this PR, but I'll need to update the link in the Meilisearch doc.

**Comment by erezrokah** [comment]
> @erezrokah I'll drop this PR, but I'll need to update the link in the Meilisearch doc.

Can you update it to https://github.com/cloudquery/cloudquery/issues/new/choose? Then we don't have to maintain it

**Pull request closed without merging**
