### PR TITLE
fix(aws_ses_active_receipt_rule_sets): Don't call DescribeActiveReceiptRuleSet on unsupported regions

### PR DESCRIPTION
**Pull request by erezrokah**
#### Summary

Fixes https://github.com/cloudquery/cloudquery/issues/5995

However I'm also happy to not do this and report the errors.

### CODE REVIEW

**Comment by hermanschaaf** [comment]
Hmm, interesting case. I think we should not report these errors, just like we don't report errors for unsupported regions for other services (usually based on https://github.com/cloudquery/cloudquery/blob/main/plugins/source/aws/client/data/partition_service_region.json). At the same time, ideally we should be able to keep this list of supported regions up-to-date in some way.

Is there a way we can automatically check the list supported regions? If not, maybe we should make the requests but ignore the error if it is "unsupported region"? That way we don't create a maintenance burden for ourselves and the code will always be correct, at the cost of a few additional requests

**Comment by erezrokah** [comment]
> Is there a way we can automatically check the list supported regions? If not, maybe we should make the requests but ignore the error if it is "unsupported region"? That way we don't create a maintenance burden for ourselves and the code will always be correct, at the cost of a few additional requests

Hmm, OK so I think the correct way to do this is to add it to the regions JSON file and add a panic when AWS adds it.
For example https://github.com/cloudquery/cloudquery/pull/5268

**Comment by hermanschaaf** [comment]
@erezrokah Yeah, though I'm not sure what key it will be added under. `email`? That's already there; this seems specific to just this one endpoint?

**Comment by erezrokah** [comment]
> @erezrokah Yeah, though I'm not sure what key it will be added under. `email`? That's already there; this seems specific to just this one endpoint?

You're right I'm just noticing that as well. It seems there isn't an automated way to get that list (other than parsing the AWS docs).

I think ignoring the error for now should work well 👍  I'll update the PR

**Comment by erezrokah** [comment]
@hermanschaaf followed up with https://github.com/cloudquery/cloudquery/pull/5997/commits/ddc2e2e5b3a3f5ed288df13972dd9638ccc6ce05

**Review by hermanschaaf — APPROVED** [review]

**Pull request merged**
