### PR TITLE
chore: Embed latest version in docs during publish

### PR DESCRIPTION
**Pull request by erezrokah**
#### Summary

Instead of doing version replacement in the UI this does it during publish.

### CODE REVIEW

**Comment by bbernays** [comment]
This lowers the likelihood of a user seeing an example configuration in the hub that is incorrect but it also means that a user can find an outdated configuration on the hub

**Comment by erezrokah** [comment]
> means that a user can find an outdated configuration on the hub

I don't think we can call it outdated. The version in the configuration will match the version you're browsing

**Comment by bbernays** [comment]
> > means that a user can find an outdated configuration on the hub
> 
> I don't think we can call it outdated. The version in the configuration will match the version you're browsing. We have a callout at if you're not browsing the latest version


If we have a config that shows how to sync `source_plugin_a` to `destination_plugin_b`. As soon as we release a new version of `destination_plugin_b` the demo config will be out of date. The callout will only be present if we have released a new `source_plugin_a`, but not if we have released a new `destination_plugin_b`.

Maybe I am missing an assumption or something else that goes into the docs generation/display.

**Comment by erezrokah** [comment]
> As soon as we release a new version of `destination_plugin_b` the demo config will be out of date

I'm not saying this replaces https://github.com/cloudquery/frontend/pull/432. We would need both for configs that reference plugins other than the one we publish.
I still think it makes sense to embed the version in the docs (like we embed it in the binary)

**Review by jackcloudquery — APPROVED** [review]

**Pull request merged**
