### PR TITLE
fix(ci): Remove `go get` to avoid unwanted changes to `go.sum` files

### PR DESCRIPTION
**Pull request by erezrokah**
#### Summary

Same as https://github.com/cloudquery/cloudquery/pull/11541 not from a fork.

>I'm actually not sure why we have this step, but it can change `go.sum` and fail the `git diff` detection step.
If we want we can add a step that does `go mod tidy` and then check for changes, which will be more accurate for checking changes to `mod` and `sum` files.

### CODE REVIEW

**Review by hermanschaaf — APPROVED** [review]
Should we perhaps be replacing it with `go mod tidy` instead of removing it?

**Comment by erezrokah** [comment]
> Should we perhaps be replacing it with `go mod tidy` instead of removing it?

Yeah I don't mind. Let me update the PR

**Comment by erezrokah** [comment]
> Should we perhaps be replacing it with `go mod tidy` instead of removing it?

Done

**Comment by erezrokah** [comment]
DuckDB if flaky regardless so I'll force merge once everything else passes

**Comment by erezrokah** [comment]
OK so it seems `go mod tidy` in CI modifies `go.sum` for the AWS source plugin, but it doesn't reproduce locally (with different Go versions).

**Comment by erezrokah** [comment]
I suggest we remove this step for now until we can figure out what's causing the changes, otherwise it's blocking PRs

**Review by disq — APPROVED** [review]

**Pull request merged**
