### PR TITLE
fix(azure-resources)!: Remove `azure_azuredata_sql_server_registrations`

### PR DESCRIPTION
**Pull request by pat-nel87**
#### Summary

Removed `azure_azuredata_sql_server_registrations` table as requested in https://github.com/cloudquery/cloudquery/issues/8343
This is my first contribution to this repository, please let me know if there is anything I should have done differently. 
Thanks!

BEGIN_COMMIT_OVERRIDE
fix(azure-resources): Remove `azure_azuredata_sql_server_registrations`

BREAKING-CHANGE: Remove `azure_azuredata_sql_server_registrations` since the API to sync it is deprecated. You should use the tables under `azurearcdata`, `azure_azurearcdata_sql_server_instances`, `azure_azurearcdata_postgres_instances` or `azure_azurearcdata_sql_managed_instances` to get the most up to date information. See more in this [Azure Go SDK issue comment](https://github.com/Azure/azure-sdk-for-go/issues/19789#issuecomment-1438803340).
END_COMMIT_OVERRIDE

### CODE REVIEW

**Comment by erezrokah** [comment]
Thanks for the PR @pat-nel87! The deleted code is also referenced here https://github.com/cloudquery/cloudquery/blob/b24f24e9775a70b19ea3705f3242d14dbc2980ba/plugins/source/azure/resources/plugin/tables.go#L127 so you should remove that.

Also can you run `make lint` and `make test` locally to ensure the CI tests will pass?

**Comment by pat-nel87** [comment]
> Thanks for the PR @pat-nel87! The deleted code is also referenced here
> 
> https://github.com/cloudquery/cloudquery/blob/b24f24e9775a70b19ea3705f3242d14dbc2980ba/plugins/source/azure/resources/plugin/tables.go#L127
> 
> so you should remove that.
> Also can you run `make lint` and `make test` locally to ensure the CI tests will pass?

Thanks for letting me take this issue! @erezrokah I've removed the references from the tables.go file and ran make lint & make test locally.

**Comment by erezrokah** [comment]
/gen sha=33709732f7a7207f8bebeb477c4416d6b754c532 plugin=azure

**Review by erezrokah — APPROVED** [review]
Thanks @pat-nel87, this looks great. Sorry for the delay in approving. We'll release this as a major version bump as it's a breaking change for the plugin

**Pull request merged**
