### PR TITLE
fix(alicloud)!: Add `billing_date` and `instance_id` to `alicloud_bss_bill_details` primary key

### PR DESCRIPTION
**Pull request by easayliu**

### CODE REVIEW

**Comment by candiduslynx** [comment]
@easayliu you would also need to run `make gen-docs` in the plugin dir & commit the changed table docs, too

**Review by candiduslynx — APPROVED** [review]

**Comment by candiduslynx** [comment]
@easayliu thanks once again for the PR!
We also noticed some similar issues with the following tables:
* `alicloud_bss_bill`
* `alicloud_bss_bill_overview`

Would you mind taking look at them, too? (asking as you clearly have much more experience with AliCloud than us)

**Comment by easayliu** [comment]
> @easayliu thanks once again for the PR! We also noticed some similar issues with the following tables:
> 
> * `alicloud_bss_bill`
> * `alicloud_bss_bill_overview`
> 
> Would you mind taking look at them, too? (asking as you clearly have much more experience with AliCloud than us)

i will check this .

**Comment by easayliu** [comment]
> @easayliu thanks once again for the PR! We also noticed some similar issues with the following tables:
> 
> * `alicloud_bss_bill`
> * `alicloud_bss_bill_overview`
> 
> Would you mind taking look at them, too? (asking as you clearly have much more experience with AliCloud than us)

Replay with my accout, i get the same `duplicate primary key`.
we will purchase multiple resource packs in one order, so we get `duplicate primary key` at table `alicloud_bss_bill_overview`.
in table `alicloud_bs_bill`,this issue will occur when refunding.
This one is good to resolve, add pk `item`. but the `alicloud_bss_bill_overview` is hard to say, this one is get the same value in every key.
Do you have any suggestions？
for example
```
{
  "Message": "Successful!",
  "RequestId": "AFBE3713-8CF3-5001-BD01-CF8372761D0C",
  "Data": {
    "BillingCycle": "2023-03",
    "TotalCount": 3,
    "AccountID": "XX",
    "PageNum": 1,
    "PageSize": 20,
    "Items": {
      "Item": [
        {
          "ProductName": "消息队列 MQ",
          "SubOrderId": "XX",
          "DeductedByCashCoupons": 0,
          "PaymentTime": "2023-03-14 18:20:47",
          "PaymentAmount": 20088.68,
          "DeductedByPrepaidCard": 0,
          "InvoiceDiscount": 3600,
          "UsageEndTime": "",
          "Item": "SubscriptionOrder",
          "SubscriptionType": "Subscription",
          "PretaxGrossAmount": 24000,
          "Currency": "CNY",
          "CommodityCode": "onsbag",
          "UsageStartTime": "",
          "AdjustAmount": 0,
          "Status": "PayFinish",
          "DeductedByCoupons": 311.32,
          "RoundDownDiscount": 0,
          "ProductDetail": "RocketMQ 4.0 标准版专用资源包（容量递减）",
          "ProductCode": "ons",
          "ProductType": "",
          "OutstandingAmount": 0,
          "PipCode": "ons",
          "PretaxAmount": 20088.68,
          "OwnerID": "XX",
          "RecordID": "XX",
          "CashAmount": 20088.68
        },
        {
          "ProductName": "消息队列 MQ",
          "SubOrderId": "XX",
          "DeductedByCashCoupons": 0,
          "PaymentTime": "2023-03-14 18:20:47",
          "PaymentAmount": 20088.68,
          "DeductedByPrepaidCard": 0,
          "InvoiceDiscount": 3600,
          "UsageEndTime": "",
          "Item": "SubscriptionOrder",
          "SubscriptionType": "Subscription",
          "PretaxGrossAmount": 24000,
          "Currency": "CNY",
          "CommodityCode": "onsbag",
          "UsageStartTime": "",
          "AdjustAmount": 0,
          "Status": "PayFinish",
          "DeductedByCoupons": 311.32,
          "RoundDownDiscount": 0,
          "ProductDetail": "RocketMQ 4.0 标准版专用资源包（容量递减）",
          "ProductCode": "ons",
          "ProductType": "",
          "OutstandingAmount": 0,
          "PipCode": "ons",
          "PretaxAmount": 20088.68,
          "OwnerID": "XX",
          "RecordID": "XX",
          "CashAmount": 20088.68
        },
        {
          "ProductName": "消息队列 MQ",
          "SubOrderId": "XX",
          "DeductedByCashCoupons": 0,
          "PaymentTime": "2023-03-14 18:20:47",
          "PaymentAmount": 12580.54,
          "DeductedByPrepaidCard": 0,
          "InvoiceDiscount": 2254.5,
          "UsageEndTime": "",
          "Item": "SubscriptionOrder",
          "SubscriptionType": "Subscription",
          "PretaxGrossAmount": 15030,
          "Currency": "CNY",
          "CommodityCode": "onsbag",
          "UsageStartTime": "",
          "AdjustAmount": 0,
          "Status": "PayFinish",
          "DeductedByCoupons": 194.96,
          "RoundDownDiscount": 0,
          "ProductDetail": "RocketMQ 4.0 标准版专用资源包（容量递减）",
          "ProductCode": "ons",
          "ProductType": "",
          "OutstandingAmount": 0,
          "PipCode": "ons",
          "PretaxAmount": 12580.54,
          "OwnerID": "XX",
          "RecordID": "XX",
          "CashAmount": 12580.54
        }
      ]
    },
    "AccountName": "XX"
  },
  "Code": "Success",
  "Success": true
}
```

**Comment by candiduslynx** [comment]
@easayliu thanks for looking into the possible PK issues!

Would you mind creating a PR for `alicloud_bs_bill` with `item` added to the primary key? (that way we can keep the acknowledgement that it was your valuable input on the issue)

For the `alicloud_bss_bill_overview` issue:
We now have `(billing_cycle,account_id,subscription_type,commodity_code,product_code,product_type,pip_code,record_id)` as the PK.
I see that there are `owner_id` and `sub_order_id` fields that might also provide additional uniqueness to the bill overview.

Would you mind testing with `jq`?
Something like:

```sh
cat output.json | jq -S -c '.Data.Items.Item[] | { SubscriptionType, CommodityCode, ProductCode, ProductType, PipCode, RecordID, OwnerID, SubOrderId }' | wc -l
cat output.json | jq -S -c '.Data.Items.Item[] | { SubscriptionType, CommodityCode, ProductCode, ProductType, PipCode, RecordID, OwnerID, SubOrderId }' | sort | uniq | wc -l
```

If the numbers are the same, it means that the uniqueness key is enough.

**Comment by easayliu** [comment]
> @easayliu thanks for looking into the possible PK issues!
> 
> Would you mind creating a PR for `alicloud_bs_bill` with `item` added to the primary key? (that way we can keep the acknowledgement that it was your valuable input on the issue)
> 
> For the `alicloud_bss_bill_overview` issue: We now have `(billing_cycle,account_id,subscription_type,commodity_code,product_code,product_type,pip_code,record_id)` as the PK. I see that there are `owner_id` and `sub_order_id` fields that might also provide additional uniqueness to the bill overview.
> 
> Would you mind testing with `jq`? Something like:
> 
> ```shell
> cat output.json | jq -S -c '.Data.Items.Item[] | { SubscriptionType, CommodityCode, ProductCode, ProductType, PipCode, RecordID, OwnerID, SubOrderId }' | wc -l
> cat output.json | jq -S -c '.Data.Items.Item[] | { SubscriptionType, CommodityCode, ProductCode, ProductType, PipCode, RecordID, OwnerID, SubOrderId }' | sort | uniq | wc -l
> ```
> 
> If the numbers are the same, it means that the uniqueness key is enough.

I`m sorry too late to reply this.
In that example, i remove number to protect.
OwnerID and RecordID is same number, It is not be able to be a PK.
Because this is order by same owner in same record.

**Pull request merged**
