### PR TITLE
feat: Configurable data folder

### PR DESCRIPTION
**Pull request by disq**
Implements #446.

```
	rootCmd.PersistentFlags().String("data-dir", "./.cq", "Directory to save and load CloudQuery persistent data to (env: CQ_DATA_DIR)")
	rootCmd.PersistentFlags().String("plugin-dir", "./.cq/providers", "Directory to save and load CloudQuery plugins from (env: CQ_PLUGIN_DIR)")
	rootCmd.PersistentFlags().String("policy-dir", "./.cq/policies", "Directory to save and load CloudQuery policies from (env: CQ_POLICY_DIR)")
```

Little bit too much. Maybe migrate away from plugin-dir and policy-dir in the future

### CODE REVIEW

**Review by spangenberg — APPROVED** [review]
LGTM

**Review by roneli — APPROVED** [review]
LGTM, agree we should deprecate plugin/policy dir or default them to data-dir/policies|plugin if the flag isn't given. Docs need update PR.

**Comment by disq** [comment]
@roneli so, I'll make those two options hidden and empty... if empty, it'll default to datadir/[policies|providers]. wdyt?

**Review by roneli — APPROVED** [review]
LGTM

**Pull request merged**
