### PR TITLE
fix: Pin indirect packages in `plugins/source/square/requirements.txt`

### PR DESCRIPTION
**Pull request by hermanschaaf**
snyk-top-banner

#### Snyk changed the following file(s):

- `plugins/source/square/requirements.txt`

<details>
<summary>⚠️ <b>Warning</b></summary>

```
squareup 29.0.0.20230720 has requirement python-dateutil~=2.8.1, but you have python-dateutil 2.9.0.post0.
pytest 7.4.4 requires tomli, which is not installed.
pytest 7.4.4 requires pluggy, which is not installed.
cloudquery-plugin-sdk 0.1.37 requires pluggy, which is not installed.
cloudquery-plugin-sdk 0.1.37 requires tomli, which is not installed.
cloudquery-plugin-sdk 0.1.37 requires numpy, which is not installed.
cloudquery-plugin-sdk 0.1.37 requires structlog, which is not installed.
cloudquery-plugin-sdk 0.1.37 requires pandas, which is not installed.
cloudquery-plugin-sdk 0.1.37 requires black, which is not installed.
cloudquery-plugin-sdk 0.1.37 requires pyarrow, which is not installed.
cloudquery-plugin-sdk 0.1.37 has requirement grpcio==1.67.1, but you have grpcio 1.62.3.
cloudquery-plugin-sdk 0.1.37 has requirement MarkupSafe==3.0.2, but you have MarkupSafe 2.1.5.
cloudquery-plugin-sdk 0.1.37 has requirement grpcio-tools==1.67.1, but you have grpcio-tools 1.62.3.
cloudquery-plugin-sdk 0.1.37 has requirement protobuf==5.28.3, but you have protobuf 4.24.4.
cloudquery-plugin-sdk 0.1.37 has requirement packaging==24.1, but you have packaging 24.0.
cloudquery-plugin-sdk 0.1.37 has requirement pytest==8.3.3, but you have pytest 7.4.4.
cloudquery-plugin-pb 0.0.37 requires pyarrow, which is not installed.
apimatic-core 0.2.16 has requirement python-dateutil~=2.8.1, but you have python-dateutil 2.9.0.post0.
apimatic-core 0.2.16 has requirement jsonpickle>=3.0.1,~=3.0.1, but you have jsonpickle 3.4.2.
```

</details>

---

> [!IMPORTANT]
>
> - Check the changes in this PR to ensure they won't cause issues with your project.
> - Max score is 1000. Note that the real score may have changed since the PR was raised.
> - This PR was automatically created by Snyk using the credentials of a real user.
> - Some vulnerabilities couldn't be fully fixed and so Snyk will still find them when the project is tested again. This may be because the vulnerability existed within more than one direct dependency, but not all of the affected dependencies could be upgraded.

---

**Note:** _You are seeing this because you or someone else with access to this repository has authorized Snyk to open fix PRs._

For more information: 
🧐 [View latest project report](https://app.snyk.io/org/cloudquery/project/0f0e53e1-3953-4bf0-9efc-72111a855b2f?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;fix-pr)
📜 [Customise PR templates](https://docs.snyk.io/scan-using-snyk/pull-requests/snyk-fix-pull-or-merge-requests/customize-pr-templates)
🛠 [Adjust project settings](https://app.snyk.io/org/cloudquery/project/0f0e53e1-3953-4bf0-9efc-72111a855b2f?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;fix-pr/settings)
📚 [Read about Snyk's upgrade logic](https://support.snyk.io/hc/en-us/articles/360003891078-Snyk-patches-to-fix-vulnerabilities)

---

**Learn how to fix vulnerabilities with free interactive lessons:**

🦉 [Arbitrary Code Execution](https://learn.snyk.io/lesson/malicious-code-injection/?loc&#x3D;fix-pr)

[//]: # 'snyk:metadata:{"customTemplate":{"variablesUsed":[],"fieldsUsed":[]},"dependencies":[{"name":"jsonpickle","from":"3.0.4","to":"3.3.0"},{"name":"requests","from":"2.31.0","to":"2.32.2"},{"name":"setuptools","from":"68.0.0","to":"70.0.0"},{"name":"urllib3","from":"2.0.7","to":"2.2.2"},{"name":"zipp","from":"3.15.0","to":"3.19.1"}],"env":"prod","issuesToFix":["SNYK-PYTHON-JSONPICKLE-8136229","SNYK-PYTHON-REQUESTS-6928867","SNYK-PYTHON-REQUESTS-6928867","SNYK-PYTHON-REQUESTS-6928867","SNYK-PYTHON-SETUPTOOLS-7448482","SNYK-PYTHON-SETUPTOOLS-7448482","SNYK-PYTHON-SETUPTOOLS-7448482","SNYK-PYTHON-URLLIB3-7267250","SNYK-PYTHON-URLLIB3-7267250","SNYK-PYTHON-URLLIB3-7267250","SNYK-PYTHON-ZIPP-7430899","SNYK-PYTHON-ZIPP-7430899","SNYK-PYTHON-ZIPP-7430899"],"prId":"1256d7f9-1280-4324-93ee-4ffc5c21615d","prPublicId":"1256d7f9-1280-4324-93ee-4ffc5c21615d","packageManager":"pip","priorityScoreList":[183,60,210,101,140],"projectPublicId":"0f0e53e1-3953-4bf0-9efc-72111a855b2f","projectUrl":"https://app.snyk.io/org/cloudquery/project/0f0e53e1-3953-4bf0-9efc-72111a855b2f?utm_source=github&utm_medium=referral&page=fix-pr","prType":"fix","templateFieldSources":{"branchName":"default","commitMessage":"default","description":"default","title":"default"},"templateVariants":["pr-warning-shown","priorityScore"],"type":"user-initiated","upgrade":[],"vulns":["SNYK-PYTHON-JSONPICKLE-8136229","SNYK-PYTHON-REQUESTS-6928867","SNYK-PYTHON-SETUPTOOLS-7448482","SNYK-PYTHON-URLLIB3-7267250","SNYK-PYTHON-ZIPP-7430899"],"patch":[],"isBreakingChange":false,"remediationStrategy":"vuln"}'

### CODE REVIEW

**Comment by hermanschaaf** [comment]
It seems like we will need to upgrade jsonpickle to >=3.3.0 in https://github.com/apimatic/core-lib-python first

**Comment by hermanschaaf** [comment]
Related: https://github.com/apimatic/core-lib-python/pull/71

**Comment by erezrokah** [comment]
Closing this for now until https://github.com/apimatic/core-lib-python/pull/71 is fixed

**Comment by erezrokah** [comment]
> Closing this for now until [apimatic/core-lib-python#71](https://github.com/apimatic/core-lib-python/pull/71) is fixed

Was done in https://github.com/apimatic/core-lib-python/pull/72

**Review by erezrokah — APPROVED** [review]

**Pull request merged**
