### PR TITLE
fix(gcp-resources): Add `update_time` to PKs of `gcp_cloudiot_device_states`

### PR DESCRIPTION
**Pull request by erezrokah**
#### Summary

Similar to https://github.com/cloudquery/cloudquery/pull/6551

### CODE REVIEW

**Comment by yevgenypats** [comment]
I think in that case the right pk is `device_name` + `updateTime`

**Comment by erezrokah** [comment]
> I think in that case the right pk is `device_name` + `updateTime`

Is it guaranteed that `updateTime` is unique? I don't know actually. Maybe it's possible to update the device twice at the same time

**Comment by erezrokah** [comment]
> I think in that case the right pk is `device_name` + `updateTime`

OK let's try with `update_time` and see how it goes

**Review by yevgenypats — APPROVED** [review]

**Comment by erezrokah** [comment]
Something is up with the test failures, not sure why it fails the PK validation

**Comment by erezrokah** [comment]
Blocked by https://github.com/cloudquery/plugin-sdk/pull/596, a bug in our type system

**Comment by erezrokah** [comment]
The real blocker is https://github.com/cloudquery/plugin-sdk/pull/597

**Comment by erezrokah** [comment]
Another correction, we should be handling this in https://github.com/cloudquery/cloudquery/blob/434fe4d15746277e903edd3ce5635fe2323ed413/plugins/source/gcp/client/transformers.go#L54. I'll check why it's not working

**Comment by erezrokah** [comment]
> Another correction, we should be handling this in

OK so I just used the wrong resolver `Path` instead of `ResolveProtoTimestamp` when redefining the column 🤦

**Pull request merged**
