### PR TITLE
feat!: Remove fail-on-error

### PR DESCRIPTION
**Pull request by yevgenypats**
Remove flag that should be the default behaviour.
If someone wants to override it he should use bash "|| true" mechanism.

This should also help remove bloat of flags that we have right now.

🎉 Thank you for making CloudQuery awesome by submitting a PR 🎉

#### Summary

---

Use the following steps to ensure your PR is ready to be reviewed

- [ ] Read the [contribution guidelines](../blob/main/.github/CONTRIBUTING.md) 🧑‍🎓
- [ ] Run `go fmt` to format your code 🖊
- [ ] Lint your changes via `golangci-lint run` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [ ] Update or add tests 🧪
- [ ] Ensure the status checks below are successful ✅

### CODE REVIEW

**Review by disq — APPROVED** [review]

**Review by erezrokah — APPROVED** [review]
Nice 👍 I suggest merging with `feat!` as this is a breaking change that can cause existing flows to fail unexpectedly (if they update to latest patch)

**Comment by erezrokah** [comment]
Also will require an update to https://docs.cloudquery.io/docs/cli/commands/fetch#usage

**Comment by yevgenypats** [comment]
> Also will require an update to https://docs.cloudquery.io/docs/cli/commands/fetch#usage

I think we should remove this part from the docs as it mostly auto generated and it get stale quickly and just adds burden. so users should just address the `--help` as well as all our tutorials that we should of-course maintain. wdyt ?

**Comment by erezrokah** [comment]
> I think we should remove this part from the docs as it mostly auto generated and it get stale quickly and just adds burden. so users should just address the `--help` as well as all our tutorials that we should of-course maintain. wdyt ?

How about we move this discussion to https://github.com/cloudquery/docs/issues/197?

**Pull request merged**
