### PR TITLE
chore(website): Upgrade Nextra and re-enable Vercel

### PR DESCRIPTION
**Pull request by hermanschaaf**

### CODE REVIEW

**Review by erezrokah — APPROVED** [review]

**Comment by erezrokah** [comment]
Nice one, we should also remove the large runner group

**Comment by hermanschaaf** [comment]
@erezrokah Good point, thanks for the reminder. I'll do that as soon as this is merged

**Comment by erezrokah** [comment]
@hermanschaaf I think we can ignore the wait for all failure as it is related to a bug in that script not handling removed workflow files

**Comment by erezrokah** [comment]
I've also re-added `Vercel` to the branch protection rules

**Pull request merged**
