### PR TITLE
fix: Add internal columns

### PR DESCRIPTION
**Pull request by BubbaJoe**
#### Summary

This fixes the `missing column _cq_source_name` error for the firestore source integration.

Use the following steps to ensure your PR is ready to be reviewed

- [x] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [x] Run `make lint` to ensure the proposed changes follow the coding style 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [x] Run `make test` to ensure the proposed changes pass the tests 🧪
- [x] If changing a source plugin run `make gen` to ensure docs are up to date 📝
- [x] Ensure the status checks below are successful ✅

Closes https://github.com/cloudquery/cloudquery/issues/11410

### CODE REVIEW

**Comment by erezrokah** [comment]
Thanks for the fix @BubbaJoe, after doing some testing we had to revert this fix, see https://github.com/cloudquery/cloudquery/pull/11452 for reasoning.

There's an ongoing issue with SDK v3 and internal columns we're working on that should address the issue. We'll deprecate the firestore versions that are broken (versions >= `v2`)

**Comment by BubbaJoe** [comment]
> Thanks for the fix @BubbaJoe, after doing some testing we had to revert this fix, see https://github.com/cloudquery/cloudquery/pull/11452 for reasoning.
> 
> 
> 
> There's an ongoing issue with SDK v3 and internal columns we're working on that should address the issue. We'll deprecate the firestore versions that are broken (versions >= `v2`)

Is reverting the correct decision? Without it it doesn't work at all and with it, it works but not internal fields which were not there before.

**Comment by erezrokah** [comment]
> Is reverting the correct decision? Without it it doesn't work at all and with it, it works but not internal fields which were not there before.

Sorry for not being it clear. It doesn't work with the fix. Writing to the destinations fails (you can see errors the logs), so the data is not saved in the destination.

**Comment by BubbaJoe** [comment]
@erezrokah Sorry I don't see the errors logs you are mentioning, when i tested it locally, it actually worked.

**Pull request merged**
