### PR TITLE
doc: Remove `isolation` column from `gcp_bigtableadmin_app_profiles`

### PR DESCRIPTION
**Pull request by candiduslynx**
Follow-up to https://github.com/cloudquery/cloudquery/pull/14925
Noticed in https://github.com/cloudquery/cloudquery/pull/15183

### CODE REVIEW

**Comment by candiduslynx** [comment]
I'm not really sure if we want this to be a breaking change or not (dropping a value (non-PK) column)

**Review by disq — APPROVED** [review]

**Comment by hermanschaaf** [comment]
This is only changing documentation, why is it breaking? If the change was already accidentally included in a previous version, what's the point of releasing a breaking change for it now? Are we going to retract the previous version?

**Comment by candiduslynx** [comment]
> This is only changing documentation, why is it breaking? If the change was already accidentally included in a previous version, what's the point of releasing a breaking change for it now? Are we going to retract the previous version?

I don't know if we're going to retract previously released version, I can make this non-brealing

**Comment by hermanschaaf** [comment]
@candiduslynx If it's only changing documentation it's still not a feature either, maybe `chore` or `doc`?

**Comment by candiduslynx** [comment]
> @candiduslynx If it's only changing documentation it's still not a feature either, maybe `chore` or `doc`?

made it `doc:`

**Review by hermanschaaf — APPROVED** [review]

**Pull request merged**
