### PR TITLE
chore: Remove deprecated terraform files

### PR DESCRIPTION
**Pull request by yevgenypats**
Those files are not used and it confuses first time contributors and/or users who looks for guidelines on how to build new plugins.

### CODE REVIEW

**Comment by erezrokah** [comment]
Can we move the files to https://github.com/cloudquery/deployments (private repo) instead? It's quite useful to have all these examples for manual testing purposes

**Comment by yevgenypats** [comment]
Im not really sure on the usefullness of that anymore but we can def backup this in the deployment repo. most of those are just copy paste from the terraform registry website .

**Review by hermanschaaf — APPROVED** [review]
Agree, let's move it somewhere where we can still access it relatively easily if we need to. Even if they are mostly copy-paste from the terraform website, it can require some fine-tuning to set _all_ the parameters properly.

**Comment by yevgenypats** [comment]
@amanenk mind taking care of that?

**Comment by amanenk** [comment]
@yevgenypats @hermanschaaf  https://github.com/cloudquery/deployments/pull/43

**Comment by erezrokah** [comment]
> Even if they are mostly copy-paste from the terraform website, it can require some fine-tuning to set _all_ the parameters properly.

Fine tuning is my experience too (mostly copy paste didn't work out of the box for me, so I need to take the full examples terraform registry has and trim it to what I wanted).

**Pull request merged**
