### PR TITLE
fix(website): Fix logos of customers on the main page

### PR DESCRIPTION
**Pull request by anton-kuptsov**
#### Summary

---

Use the following steps to ensure your PR is ready to be reviewed

- [ ] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [ ] Test locally on your own infrastructure
- [ ] Run `go fmt` to format your code 🖊
- [ ] Lint your changes via `golangci-lint run` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation)) 
- [ ] Update or add tests 🧪
- [ ] Ensure the status checks below are successful ✅

### CODE REVIEW

**Comment by yevgenypats** [comment]
Looks good. Given the Vercel is still not running can you please post a picture of how it looks like? Thx!

**Comment by anton-kuptsov** [comment]
> Looks good. Given the Vercel is still not running can you please post a picture of how it looks like? Thx!

Yes, sure!

image
image
image

**Comment by yevgenypats** [comment]
Looks like something is off with `AutoDesk` each letter is different color (prob something I did) - can you please fix it?

**Comment by anton-kuptsov** [comment]
image

**Comment by anton-kuptsov** [comment]
image
image
image
image

**Pull request merged**
