### PR TITLE
feat(aws): Add aws/iam/instance_profiles table

### PR DESCRIPTION
**Pull request by ryu-ke**
#### Summary

Added `iam_instance_profiles` table of AWS plugin.
This is a resource to bind iam roles to an EC2 instance.
https://docs.aws.amazon.com/IAM/latest/APIReference/API_InstanceProfile.html

- [x] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [x] Test locally on your own infrastructure
- [x] Run `go fmt` to format your code 🖊
- [x] Lint your changes via `golangci-lint run` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [x] Update or add tests 🧪
- [ ] Ensure the status checks below are successful ✅

### CODE REVIEW

**Review by amanenk — APPROVED** [review]
Nice work! Looks good to me.

**Comment by ryu-ke** [comment]
@amanenk Thank you for your look!! 
Execute me for asking, how can I resolve Vercel authorization error?

**Comment by erezrokah** [comment]
> Execute me for asking, how can I resolve Vercel authorization error?

Sorry for the trouble, we had to manually approve it on Vercel's side

**Review by hermanschaaf — APPROVED** [review]
Looks great, thank you for the contribution @ryu-ke!

**Comment by ryu-ke** [comment]
Appreciate your support!! :)

**Pull request merged**
