### PR TITLE
feat(aws): Use PreResourceResolver when necessary, remove ListAndDetailResolver

### PR DESCRIPTION
**Pull request by disq**
More here https://github.com/cloudquery/cloudquery/pull/2461

**BEWARE** merging this before updating the plugin-sdk for "PreResourceResolver parallelism" will cause performance regressions. (#2461 doesn't have that issue, as those resources are already linear)

### CODE REVIEW

**Comment by yevgenypats** [comment]
This should go in with https://github.com/cloudquery/plugin-sdk/pull/268

**Review by yevgenypats — APPROVED** [review]

**Comment by disq** [comment]
Waiting for https://github.com/cloudquery/cloudquery/pull/2590 before we can merge this.

**Comment by disq** [comment]
Waiting for #2610

**Comment by disq** [comment]
Now waiting for #2661

**Review by hermanschaaf — APPROVED** [review]
👍

**Pull request merged**
