### PR TITLE
fix(azure): Use lowercase namespaces

### PR DESCRIPTION
**Pull request by yevgenypats**
This should fix some of the missing tables we were seeing in azure. apparently namespaces are not consistent and can be lowered case, camel cased, something else... So we normalize them all to lower-case (given they are case insensitive) on the client side.

### CODE REVIEW

**Comment by yevgenypats** [comment]
Closes:
 https://github.com/cloudquery/cloudquery/pull/5761
 https://github.com/cloudquery/cloudquery/issues/5683

**Review by erezrokah — APPROVED** [review]
Looks good but I think this fixes https://github.com/cloudquery/cloudquery/issues/5760 and https://github.com/cloudquery/cloudquery/pull/5761, but not https://github.com/cloudquery/cloudquery/issues/5683 as for https://github.com/cloudquery/cloudquery/issues/5683 we still need https://github.com/cloudquery/cloudquery/pull/5758.

Also could we drop the namespace multiplexer altogether? We don't use the namespace in the List API calls. I tried it for a few API calls in https://github.com/cloudquery/cloudquery/pull/5758 and it doesn't generate a lot of errors (only one errored out with a "not registered service").

The last comment is more a product decision, dropping the namespace multiplexer will make the Azure plugin consistent with GCP's default behavior

**Comment by yevgenypats** [comment]
> 

I don't think we need to drop the multiplexer because otherwise azure will hit disabled APIs and this will be (really) slow. we were actually trying to implement this in GCP but with no success so far due to some issues with their list disabled APIs. 

Regarding the issue - Im not sure what the customer is complaining about - is he not seeing anything at all? specific table. I think the issue needs more elaboration.

**Comment by yevgenypats** [comment]
> ### This PR has the following changes to source plugin(s) tables:
> * ⚠️ BREAKING CHANGE: Table `azure_sql_deleted_servers` was removed

@erezrokah Can we not mark it as breaking. This table was never working.

**Comment by yevgenypats** [comment]
> > ### This PR has the following changes to source plugin(s) tables:
> > 
> > * ⚠️ BREAKING CHANGE: Table `azure_sql_deleted_servers` was removed
> 
> @erezrokah Can we not mark it as breaking? This table was never working.

**Comment by erezrokah** [comment]
@yevgenypats This comment is just FYI, as long as the PR title/body doesn't say it's breaking it won't bump the major version

**Comment by erezrokah** [comment]
> I'm not sure what the customer is reporting about

There are 2 separate issues:
1. We don't provide any information when we filter the tables based on the provider being registered, so users can't know why the tables are not synced. This is fixed in https://github.com/cloudquery/cloudquery/pull/5758
2. We were using the wrong namespaces (https://github.com/cloudquery/cloudquery/issues/5760) which this PR closes

**Pull request merged**
