### PR TITLE
chore(site-versions): Add latest redirect

### PR DESCRIPTION
**Pull request by erezrokah**
#### Summary

Creates our own latest link for the CLI

### CODE REVIEW

**Comment by erezrokah** [comment]
https://cloudquery-versions-bpyf3rkbi-cloudquery.vercel.app/latest/v1/cloudquery_Darwin_arm64 seems to work 🚀

**Review by yevgenypats — APPROVED** [review]
🎸  Very Nice!

**Comment by yevgenypats** [comment]
@erezrokah should we merge it to the v1  branch as well?

**Comment by erezrokah** [comment]
> @erezrokah should we merge it to the v1 branch as well?

Which branch is that and how it gets deploys? Is it https://github.com/cloudquery/cloudquery/tree/feat/docs_v2?

**Pull request merged**
