### PR TITLE
feat: Added ability to configure proxy via config file

### LINKED ISSUE #499: Ensure Support for HTTP Proxy
### Is your feature request related to a problem? Please describe.

Many organizations require all traffic to go through specific proxies, we need to ensure that users are able to direct their traffic to these proxies

### Describe the solution you'd like

- Users should be able to define proxy settings via environment variables as well as the config.hcl
- Providers need to respect these settings as well

### PR DESCRIPTION
**Pull request by amanenk**
🎉 Thank you for making CloudQuery awesome by submitting a PR 🎉

#### Summary

I have tested proxy configuration with cq-provider-aws cq-provider-gcp cq-provider-azure. All of them work with proxy setting environment variables so they can be used to set proxy config.  Added proxy block to hcl config. added setting of proxy env vars if they are exist in config.

closes #499 

---

Use the following steps to ensure your PR is ready to be reviewed

- [x] Read the [contribution guidelines](../blob/main/.github/CONTRIBUTING.md) 🧑‍🎓
- [x] Run `go fmt` to format your code 🖊
- [x] Lint your changes via `golangci-lint run` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [x] Update or add tests 🧪
- [x] Ensure the status checks below are successful ✅

### CODE REVIEW

**Comment by erezrokah** [comment]
I might be missing something here, but if users can use env variables for configure a proxy, what's the use case for having it in our configuration file too? Won't using `HTTP_PROXY=<proxy> cloudquery fetch` work?

**Comment by amanenk** [comment]
> I might be missing something here, but if users can use env variables for configure a proxy, what's the use case for having it in our configuration file too? Won't using `HTTP_PROXY=<proxy> cloudquery fetch` work?

The example you provided will work.
I forgot to link an issue for this PR. Ability to set proxy in config file was in requirements of the issue (#499)

**Comment by bbernays** [comment]
If we are just setting the os environment variables, I am not sure that we should own that complexity in CQ rather than just verifying and documenting that all of our http clients respect those HTTP Variables

**Comment by erezrokah** [comment]
@amanenk what do you think about closing this PR in favor of documenting the env variables support?

**Pull request closed without merging**
