### PR TITLE
Add organizations

### PR DESCRIPTION
**Pull request by yevgenypats**
Continue PR: https://github.com/cloudquery/cloudquery/pull/51

### CODE REVIEW

**Comment by yevgenypats** [comment]
@mvaerle I've added a small commit on top of your PR. Can you please test it? I think it's almost ready.

**Comment by mvaerle** [comment]
@yevgenypats just tested it and it works for me, I don't get any double rows anymore. I ran it multiple times as well to test that.

Note that I still get a lot of warnings, since in `config.yml` I've added all the accounts and this call only works for two of those. For all the other accounts it throws an `AccessDeniedException`. Note sure what the best approach there is.

**Comment by yevgenypats** [comment]
@mvaerle Thanks for testing! Can you share with me the snippet of the log (you can redact sensitive information). I think you can ignore this exception I just want to make sure it just print the error and continues and not stops the fetching.

**Comment by yevgenypats** [comment]
I've changed the Warning to Info and added an account_id so it will be more verbose. you can ignore this message. Rebasing and releasing!

**Pull request merged**
