### PR TITLE
chore(website): Remove `title` from code blocks

### PR DESCRIPTION
**Pull request by candiduslynx**

### CODE REVIEW

**Comment by candiduslynx** [comment]
Currently the code blocks with `copy` and title don't show properly.
@hermanschaaf @erezrokah 
See https://www.cloudquery.io/how-to-guides/how-to-load-infrastructure-data-into-athena

**Comment by hermanschaaf** [comment]
Nice catch! I'm fairly sure this used to work... was it broken by a recent upgrade maybe?

**Review by hermanschaaf — APPROVED** [review]

**Comment by hermanschaaf** [comment]
Let's remove it for now so the code blocks render at least

**Comment by candiduslynx** [comment]
@erezrokah could you take a look into that? Additionally, do we need to update other docs as well?

**Comment by hermanschaaf** [comment]
@candiduslynx It seems like it's mostly me who's been using this feature, so only some docs I touched have it. But some are quite important, like the AWS overview. So if it's not easy to fix we should remove it from there as well for the time being

**Comment by hermanschaaf** [comment]
I'll raise a PR to remove it for the time being

**Pull request merged**
