### PR TITLE
feat: Add destination when generating sources

### PR DESCRIPTION
**Pull request by erezrokah**
#### Summary

Requires https://github.com/cloudquery/plugin-sdk/pull/120

Somehow fixes https://github.com/cloudquery/cloudquery/issues/1808.
When generating sources, if there's a destination generated already, add it to the source configuration.

Then I think our docs should first instruct users to generate the destination, then the sources.

---

Use the following steps to ensure your PR is ready to be reviewed

- [x] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [x] Test locally on your own infrastructure
- [x] Run `go fmt` to format your code 🖊
- [x] Lint your changes via `golangci-lint run` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation)) 
- [x] Update or add tests 🧪
- [x] Ensure the status checks below are successful ✅

### CODE REVIEW

**Review by yevgenypats — APPROVED** [review]
I think this looks good! but I think we have to be cautions with `gen` turning into a product of itself which generates configs for various use-cases and so on so really important to keep it simple as I would even go far that `gen` is even not mandatory on it's own as it's quite common in most cases for users to create configs from documentation rather from commands that auto generate configs.

**Comment by erezrokah** [comment]
> I think this looks good! but I think we have to be cautions with `gen` turning into a product of itself which generates configs for various use-cases and so on so really important to keep it simple as I would even go far that `gen` is even not mandatory on it's own as it's quite common in most cases for users to create configs from documentation rather from commands that auto generate configs.

💯 This is a feature on its own. I'm trying to prevent the back and forth between CLI commands and manually editing files.
Another approach would be to make config creation/editing DX better (i.e. expose schema, have auto completion in IDE), but I think at the moment this is the fastest thing we can do to improve onboarding.

**Comment by erezrokah** [comment]
> Because for example how do we know the user wants to sync the source with all destinations? so either he will have to add a destination or to delete a destination (not sure which is better I think to explicitly add might be better and the more secure way)

Yes I think this feature might change when we have more destinations (for example I think we can let the user chose from a list)

**Comment by erezrokah** [comment]
Also waiting on https://github.com/cloudquery/plugin-sdk/pull/120 to merge this

**Comment by yevgenypats** [comment]
> > Because for example how do we know the user wants to sync the source with all destinations? so either he will have to add a destination or to delete a destination (not sure which is better I think to explicitly add might be better and the more secure way)
> 
> Yes I think this feature might change when we have more destinations (for example we can let the user chose from a list)

I wouldn't go into the rabbit hole of adding more features like choosing from a list but rather just output the config and make this feature end at this. Im even at the opinion that the `gen` command is a bit too much but given we already have it and people like it we can keep it but wouldn't work on adding more features and interactivity to that as it's not the main goal of CQ (other we branch to auto-generating config product)

**Review by yevgenypats — CHANGES_REQUESTED** [review]
Actually second thought here - Let's keep the `gen` command write only without reading the current directly I think it is really important to keep bugs at bay and things like oh it read a different directory and so on. I think the current `gen` command is way more advanced to the current status of the tool anyway.

**Comment by erezrokah** [comment]
Got it, I'll close the PR

**Pull request closed without merging**
