### PR TITLE
feat(firestore): Add firestore source

### PR DESCRIPTION
**Pull request by BubbaJoe**
#### Summary
Adds firebase source #9414 

- [x] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [x] Run `make lint` to ensure the proposed changes follow the coding style 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [x] Run `make test` to ensure the proposed changes pass the tests 🧪
- [x] If changing a source plugin run `make gen` to ensure docs are up to date 📝
- [x] Ensure the status checks below are successful ✅

### CODE REVIEW

**Comment by disq** [comment]
Hi @BubbaJoe, would you consider maintaining this plugin, by hosting it in its own repository and handling the releases/updates/issues? One such plugin is the [SharePoint source plugin](https://github.com/koltyakov/cq-source-sharepoint) (which is also a community plugin) and another is [Simple Analytics plugin](https://github.com/simpleanalytics/cq-source-simpleanalytics), a partner-maintained plugin. We can then add it to the [Community Plugins](https://www.cloudquery.io/docs/plugins/sources/overview#community-plugins) section in our docs and you can basically control your own release cycle.

All you would have to do is to open a new repo called `cq-source-firestore`, and add the changes under `plugin/source/firestore` to the root of that repository, with possibly some changes in `.github/` and `.goreleaser.yml` (which can be copied from the SharePoint plugin, with minor modifications) and you'd be set. Then, after tagging a release, the config to use the plugin would be something like:

```yaml
kind: source
spec:
  name: "firestore"
  registry: "github"
  path: "your-repo-org/firestore"
  version: "v1.0.0" # provide the latest stable version
  destinations: ["postgresql"] # provide the list of used destinations
  spec:
# ...
```

Let me know what you think.

**Comment by BubbaJoe** [comment]
@disq Tbh, i don't know if that's a good idea. Perhaps if this was a database which was not so popular, I would consider it, but I think it was be in Cloudquery's best interest to keep it here.

**Comment by BubbaJoe** [comment]
@disq For testing, do i need to include some docker compose for setting up a local instance (emulator in firestore's case)?

**Comment by disq** [comment]
> @disq For testing, do i need to include some docker compose for setting up a local instance (emulator in firestore's case)?

@BubbaJoe Yes that would be the way to test, [here](https://github.com/cloudquery/cloudquery/blob/main/.github/workflows/source_postgresql.yml) are [a few](https://github.com/cloudquery/cloudquery/blob/main/.github/workflows/source_mysql.yml) examples from the PostgreSQL and MySQL source plugins respectively.

**Review by disq — APPROVED** [review]

**Comment by erezrokah** [comment]
Hi @BubbaJoe thanks for the PR and @disq for the review. I followed up with a docs PR in https://github.com/cloudquery/cloudquery/pull/10007, can you please help me ensure it makes sense?

**Comment by erezrokah** [comment]
Officially released in https://github.com/cloudquery/cloudquery/releases/tag/plugins-source-firestore-v1.0.0, great work @BubbaJoe and @disq 🎸

**Pull request merged**
