### PR TITLE
feat(aws): Add networkfirewall resources

### PR DESCRIPTION
**Pull request by rynsuke**
#### Summary
Add the following resources of AWS Network Firewall:
- FirewallPolicy
- RuleGroup

#### Checklist
- [x] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [x] Run `make lint` to ensure the proposed changes follow the coding style 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [x] Run `make test` to ensure the proposed changes pass the tests 🧪
- [x] If changing a source plugin run `make gen` to ensure docs are up to date 📝
- [x] Ensure the status checks below are successful ✅

### CODE REVIEW

**Review by hermanschaaf — APPROVED** [review]
Looks great, thank you @rynsuke ! 

I added a couple of commits to clean up some minor things that I didn't want to bother you with (fix the docs linting errors, use paginators, etc), so I think this is good to merge 👍

**Comment by rynsuke** [comment]
Awesome!! Thank you so much for your great support! 😆

**Comment by hermanschaaf** [comment]
Thanks @rynsuke, looks like there was a transient error with the GitHub API. I ran the workflow again and it passed this time 👍

**Comment by rynsuke** [comment]
Thanks a lot!!

**Pull request merged**
