### PR TITLE
fix: Data race on transformers pipeline closed check

### PR DESCRIPTION
**Pull request by disq**
Fixes the data race on `isClosed`, which we introduced in https://github.com/cloudquery/cloudquery/pull/19105

```
2024-09-11T16:10:36Z INF top level table resolver started client=Client#4 invocation_id=0ed60c97-05cf-4365-9789-e9fe27561951 module=test-source table=test_paid_table
panic: send on closed channel

goroutine 45 [running]:
github.com/cloudquery/cloudquery/cli/internal/transformerpipeline.(*identityTransformer).Send(0x14000a26a20?, 0x10580de10?)
        /Users/me/go/src/github.com/cloudquery/cq/cli/internal/transformerpipeline/identity.go:24 +0x28
github.com/cloudquery/cloudquery/cli/internal/transformerpipeline.(*TransformerPipeline).Send(0x140000c4460, {0x14000a6ea80, 0x1d48, 0x2a80})
        /Users/me/go/src/github.com/cloudquery/cq/cli/internal/transformerpipeline/pipeline.go:76 +0xcc
github.com/cloudquery/cloudquery/cli/cmd.syncConnectionV3.func6()
        /Users/me/go/src/github.com/cloudquery/cq/cli/cmd/sync_v3.go:422 +0x96c
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /Users/me/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:78 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
        /Users/me/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:75 +0x98


==================
WARNING: DATA RACE
Read at 0x00c00057c868 by goroutine 71:
  github.com/cloudquery/cloudquery/cli/internal/transformerpipeline.(*TransformerPipeline).Send()
      /Users/me/go/src/github.com/cloudquery/cq/cli/internal/transformerpipeline/pipeline.go:72 +0xb4
  github.com/cloudquery/cloudquery/cli/cmd.syncConnectionV3.func6()
      /Users/me/go/src/github.com/cloudquery/cq/cli/cmd/sync_v3.go:422 +0xcfc
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /Users/me/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:78 +0x7c

Previous write at 0x00c00057c868 by goroutine 72:
  github.com/cloudquery/cloudquery/cli/internal/transformerpipeline.(*TransformerPipeline).Close()
      /Users/me/go/src/github.com/cloudquery/cq/cli/internal/transformerpipeline/pipeline.go:98 +0x298
  github.com/cloudquery/cloudquery/cli/cmd.syncConnectionV3.func5()
      /Users/me/go/src/github.com/cloudquery/cq/cli/cmd/sync_v3.go:373 +0x204
  github.com/cloudquery/cloudquery/cli/cmd.syncConnectionV3.(*TransformerPipeline).OnOutput.func23()
      /Users/me/go/src/github.com/cloudquery/cq/cli/internal/transformerpipeline/pipeline.go:84 +0x5c
  github.com/cloudquery/cloudquery/cli/internal/transformerpipeline.clientWrapper.startBlocking()
      /Users/me/go/src/github.com/cloudquery/cq/cli/internal/transformerpipeline/pipeline.go:122 +0x1d8
  github.com/cloudquery/cloudquery/cli/internal/transformerpipeline.clientWrapper.startBlocking-fm()
      <autogenerated>:1 +0x60
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /Users/me/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:78 +0x7c

Goroutine 71 (running) created at:
  golang.org/x/sync/errgroup.(*Group).Go()
      /Users/me/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:75 +0x10c
  github.com/cloudquery/cloudquery/cli/cmd.syncConnectionV3()
      /Users/me/go/src/github.com/cloudquery/cq/cli/cmd/sync_v3.go:386 +0x3a68
  github.com/cloudquery/cloudquery/cli/cmd.sync()
      /Users/me/go/src/github.com/cloudquery/cq/cli/cmd/sync.go:377 +0x3d64
  github.com/spf13/cobra.(*Command).execute()
      /Users/me/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0xbc4
  github.com/spf13/cobra.(*Command).ExecuteC()
      /Users/me/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x4b8
  github.com/spf13/cobra.(*Command).Execute()
      /Users/me/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041 +0x74
  github.com/spf13/cobra.(*Command).ExecuteContext()
      /Users/me/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1034 +0x18
  main.executeRootCmdWithContext()
      /Users/me/go/src/github.com/cloudquery/cq/cli/main.go:38 +0x2e0
  main.main()
      /Users/me/go/src/github.com/cloudquery/cq/cli/main.go:65 +0x130

Goroutine 72 (finished) created at:
  golang.org/x/sync/errgroup.(*Group).Go()
      /Users/me/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:75 +0x10c
  github.com/cloudquery/cloudquery/cli/internal/transformerpipeline.(*TransformerPipeline).RunBlocking()
      /Users/me/go/src/github.com/cloudquery/cq/cli/internal/transformerpipeline/pipeline.go:61 +0x78
  github.com/cloudquery/cloudquery/cli/internal/transformerpipeline.(*TransformerPipeline).RunBlocking-fm()
      <autogenerated>:1 +0x34
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /Users/me/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:78 +0x7c
==================
```

### CODE REVIEW

**Comment by disq** [comment]
Probably doesn't really matter because the whole isClosed check is not doing what we want it to do reliably.

**Comment by erezrokah** [comment]
How can we reproduce the data race? Do we need to add a test for it?

**Comment by disq** [comment]
@erezrokah Build the cli with `go build -race .` and then use this config:
```yaml
kind: source
spec:
  name: test
  registry: cloudquery
  path: cloudquery/test
  version: v4.3.6
  tables: [ test_paid_table ]
  destinations: ["test"]
  spec:
    num_rows: 50000
    num_clients: 40
---
kind: destination
spec:
  name: test
  path: cloudquery/test
  registry: cloudquery
  version: v2.4.0
  spec:
    error_on_insert: true
    error_on_write: false
    error_on_migrate: false
    batch_writer: false
```

**Comment by marianogappa** [comment]
Closing this in favor of https://github.com/cloudquery/cloudquery/pull/19165 cc @disq

**Pull request closed without merging**
