### PR TITLE
fix(aws): Update EC2 Tag structure

### PR DESCRIPTION
**Pull request by bbernays**

### CODE REVIEW

**Review by disq — APPROVED** [review]

**Comment by hermanschaaf** [comment]
Hmm, I assume this was a regression - how did it happen? Was it during the transformer refactor?

**Review by hermanschaaf — APPROVED** [review]

**Comment by bbernays** [comment]
> Hmm, I assume this was a regression - how did it happen? Was it during the transformer refactor?

Yeah it was during the transformer refactor... I am trying to figure out how I can verify that this was in fact the only miss... Any ideas?

**Comment by hermanschaaf** [comment]
@bbernays I think we pretty much have to look for all `tags` columns that don't have a custom resolver. The best thing might be to write a test for AWS specifically that checks that every `tags` column is either using a custom resolver or maps to a `map[string]string`... might take some doing, but seems possible

**Comment by candiduslynx** [comment]
Could we also add a resolver transformer that will check if the fields is a JSON field, and, in that case, verify that we're dealing with tags in form of kv pairs slice? This way it'll apply to all proper fields and we would need to do this fix once.

**Pull request merged**
