### PR TITLE
fix(resources): Link to gcp project description

### PR DESCRIPTION
**Pull request by RichardoC**
#### Summary

Currently the GCP projects have no description, so updating this to match other resources

### CODE REVIEW

**Review by erezrokah — APPROVED** [review]
Thanks @RichardoC 🚀

**Comment by erezrokah** [comment]
Hi @RichardoC, looks we need to update the table docs to match this change. You can do it by running `make gen` from the plugin directory (`plugins/source/gcp`).

I tried to do it using some automation we have but it looks like maintainers can't edit the PR. You might need to enable it via https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by RichardoC** [comment]
I've updated to allow edits. When I tried to generate the markdown I got the following, with the most recently released cloudquery

```bash
make gen
go run client/spec/gen/main.go
Generating JSON schema for plugin spec
go build -o gcp
rm -rf docs/tables
cloudquery tables --format markdown --output-dir docs test/config.yml
/usr/bin/cloudquery: 1: Syntax error: "(" unexpected
make: *** [Makefile:23: gen-docs] Error 2
```

**Pull request merged**
