### PR TITLE
feat(github): Add `github_repository_branches` table

### PR DESCRIPTION
**Pull request by patriknordlen**
#### Summary
This PR addresses #10020 by adding the table `github_repository_branches` containing information retrieved from the `/repos/{owner}/{repo}/branches` and `/repos/{owner}/{repo}/branches/{branch}/protection` endpoints for each repository and branch.

- [X] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [X] Run `make lint` to ensure the proposed changes follow the coding style 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [X] Run `make test` to ensure the proposed changes pass the tests 🧪
- [X] If changing a source plugin run `make gen` to ensure docs are up to date 📝
- [X] Ensure the status checks below are successful ✅

### CODE REVIEW

**Review by candiduslynx — APPROVED** [review]

**Comment by candiduslynx** [comment]
Hi @patriknordlen!

Thanks for the PR!

Kindly, ensure the following:
* you ran `make gen` in the plugin dir
* fix lint (from plugin dir run `golangci-lint run --config ../../.golangci.yml --fix`)
* commit all the changes

**Comment by patriknordlen** [comment]
> Hi @patriknordlen!
> 
> Thanks for the PR!
> 
> Kindly, ensure the following:
> 
>     * you ran `make gen` in the plugin dir
> 
>     * fix lint (from plugin dir run `golangci-lint run --config ../../.golangci.yml --fix`)
> 
>     * commit all the changes

Thanks for the review! I've addressed the format issues highlighted by `golangci-lint` and committed the fix.

**Review by candiduslynx — APPROVED** [review]

**Comment by erezrokah** [comment]
Hi @patriknordlen thanks for the PR and @candiduslynx for the review. FYI `v49` introduced a [breaking change](https://github.com/google/go-github/pull/2597/files#diff-68dd5a4c8680280d10f33a336eb55e2965d261c0ae6a027638b07f6dbb3dc92bR40) in one of the structs we use.

However since the change was to an internal struct that we serialize to JSON as a key value map, and the values seem to be the same, this seems non breaking for us.

**Comment by patriknordlen** [comment]
> Hi @patriknordlen thanks for the PR and @candiduslynx for the review. FYI `v49` introduced a [breaking change](https://github.com/google/go-github/pull/2597/files#diff-68dd5a4c8680280d10f33a336eb55e2965d261c0ae6a027638b07f6dbb3dc92bR40) in one of the structs we use.
> 
> However since the change was to an internal struct that we serialize to JSON as a key value map, and the values seem to be the same, this seems non breaking for us.

I see! The reason for bumping to v49 in this PR was that it addressed a breaking change in Github's API endpoint for fetching branch protections. https://github.com/google/go-github/issues/2612

**Comment by erezrokah** [comment]
> I see! The reason for bumping to v49 in this PR was that it addressed a breaking change in Github's API endpoint for fetching branch protections. [google/go-github#2612](https://github.com/google/go-github/issues/2612)

Nice! Thanks for the context, makes sense. I'm glad it all worked out (worst case we'd be making a major bump of the plugin, but it's not necessary here)

**Pull request merged**
