### PR TITLE
fix: RDS fixes

### PR DESCRIPTION
**Pull request by shimonp21**
#### Summary

See individual commits please :)

### CODE REVIEW

**Comment by hermanschaaf** [comment]
@shimonp21 I haven't looked into this yet; what happened here, and how do you know this is dead code?

**Comment by shimonp21** [comment]
Looked at the reference - There is no reason for the type-switch and for one of the functions, because `fetchRdsClusterParameters` is only called from one place.

**Comment by shimonp21** [comment]
Also tested with logs and saw that one of the paths is never called

**Comment by shimonp21** [comment]
@hermanschaaf, @bbernays  - Added one more fix here - PTAL

**Review by hermanschaaf — APPROVED** [review]

**Pull request merged**
