### PR TITLE
fix: Improperly Configured Service Clients

### PR DESCRIPTION
**Pull request by bbernays**
#### Summary

Fixes panics in resources

### CODE REVIEW

**Review by erezrokah — APPROVED** [review]

**Comment by erezrokah** [comment]
This should be caught by adding mock tests to these resources (I think)

**Comment by bbernays** [comment]
> This should be caught by adding mock tests to these resources (I think)

I would have expected the same thing, but I don't think it is as all of these resources have mock tests:
https://github.com/cloudquery/cloudquery/blob/b448bc6cebdf7ddbcdcd9fedb6ebb5fa427821f2/plugins/source/aws/resources/services/cloudhsmv2/backups_mock_test.go

**Comment by erezrokah** [comment]
> I would have expected the same thing, but I don't think it is as all of these resources have mock tests:
> https://github.com/cloudquery/cloudquery/blob/b448bc6cebdf7ddbcdcd9fedb6ebb5fa427821f2/plugins/source/aws/resources/services/cloudhsmv2/backups_mock_test.go

Yeah I was wrong. Mock tests won't catch this as we create mock services in the mock tests

**Comment by yevgenypats** [comment]
Seems like a good place to either add test or maybe let the codegen output those same as in gcp plugin

**Comment by bbernays** [comment]
> Seems like a good place to either add test or maybe let the codegen output those same as in gcp plugin

@yevgenypats - Created an issue to track this

**Pull request merged**
