### PR TITLE
Add FreeBSD Package Mention to README.md

### PR DESCRIPTION
**Pull request by neelchauhan**
I maintain the FreeBSD Port/Package for cloudquery. We should mention it in README.md.

### CODE REVIEW

**Comment by yevgenypats** [comment]
Hi @neelchauhan Thanks for contribution! A few questions, comments:

One of the strength of Go that it can easily compile to any architecture and OS very easily. So if freeBSD is needed we can easily add it to the release. This will also remove the need to maintain a port and for the user to compile it locally instead of just running a pre-compiled binary. Let me know what you think?

**Comment by neelchauhan** [comment]
FYI "FreeBSD Ports" is the name of the packaging system used on FreeBSD, like Debian/Ubuntu `apt-get`, macOS `homebrew`, or Arch `pacman`.

**Comment by yevgenypats** [comment]
Yes, I know but still it will be easier to package a pre-compiled binary then to compile it. Also, I believe once you add only the pre-compiled binary this line: `make config-recursive install clean` won't be necessary

**Comment by yevgenypats** [comment]
Closing for now.

**Pull request closed without merging**
