### PR TITLE
feat(aws): Step Function Resources

### PR DESCRIPTION
**Pull request by bbernays**

### CODE REVIEW

**Review by erezrokah — APPROVED** [review]

**Comment by koltyakov** [comment]
@bbernays I'm trying to get step functions related data and experiencing an error:

2023-02-14T22:27:15Z ERR table resolver finished with error error="operation error SFN: ListExecutions, https response error StatusCode: 400, RequestID: 41e6678b-10d9-4924-8a4b-927966b86d51, ValidationException: Must provide a StateMachine ARN or MapRun ARN" client=***:us-east-1 module=aws-src table=aws_stepfunctions_executions

The config is:

```yml
kind: source
spec:
  name: "aws"
  path: "cloudquery/aws"
  version: "v14.0.0"
  tables: ["aws_stepfunctions_state_machines", "aws_stepfunctions_activities", "aws_stepfunctions_executions", "aws_stepfunctions_executions_map_runs"]
  destinations: ["postgresql"]
  spec:
    regions: 
      - us-east-1
```

Sync completed successfully. Resources: 3, Errors: 1, Panics: 0, Time: 3s

Could you please suggest am I missing something?

**Comment by bbernays** [comment]
@koltyakov - Looking into this now

**Comment by bbernays** [comment]
@koltyakov - Can confirm there is an issue with the code. Looking into this some more. Will ping you when we release a new (fixed) version

**Comment by koltyakov** [comment]
Thank you @bbernays!

**Comment by bbernays** [comment]
@koltyakov - We have released a new version of the AWS plugin (`v15.0.0`) that contains the appropriate fixes for the `step_function` issues you were facing yesterday. If you have any issues with it please open a new issue and we would be happy to look into it!

**Comment by koltyakov** [comment]
You are fantastic! Thank you! Confirming it works now with v15.0.0 and amended tables list.

P.S. Sorry it's taking time to check it's actually complete with all step functions execution I have `Syncing resources... (26529/-, 0 resources/hr) [42m48s]`.

**Pull request merged**
