### PR TITLE
chore(tests): Try parallel testing

### PR DESCRIPTION
**Pull request by disq**
Try parallel testing on all tests using mock test helpers.

### CODE REVIEW

**Review by erezrokah — APPROVED** [review]

**Comment by erezrokah** [comment]
For AWS tests changed from `2m 6s` to `1m 48s`:
https://github.com/cloudquery/cloudquery/actions/runs/3243124043/jobs/5317379722
https://github.com/cloudquery/cloudquery/actions/runs/3243092646/jobs/5317306478

But that's only one run

**Comment by yevgenypats** [comment]
> For AWS tests changed from `2m 6s` to `1m 48s`: https://github.com/cloudquery/cloudquery/actions/runs/3243124043/jobs/5317379722 https://github.com/cloudquery/cloudquery/actions/runs/3243092646/jobs/5317306478
> 
> But that's only one run

@erezrokah  maybe increasing `GOMAXPROCS ` to 4 or 8 will help ?

**Review by yevgenypats — CHANGES_REQUESTED** [review]
I think this should into the SDK `TestSourcePluginSync`

**Comment by disq** [comment]
> TestSourcePluginSync

but that method doesn't take an option, to override (disable) parallel testing?

**Comment by yevgenypats** [comment]
> > TestSourcePluginSync
> 
> but that method doesn't take an option, to override (disable) parallel testing?

I think then it would be great case to introduce option and make it default enabled :)

**Comment by erezrokah** [comment]
>@erezrokah maybe increasing GOMAXPROCS to 4 or 8 will help ?

Maybe GitHub machines are not strong enough to take advantage. Regardless this is probably good for local dev machiens

**Pull request closed without merging**
