### PR TITLE
fix: !!!DON'T MERGE!!! Test authorization logic

### PR DESCRIPTION
**Pull request by janory**
This is a to test PR to Vercel's authorization request logic.

### CODE REVIEW

**Comment by janory** [comment]
> > This is a to test PR to Vercel's authorization request logic.
> 
> Hi @janory 👋 We have Git Fork Protection disabled. Would you like me to re-enable for testing purposes?

Hi @erezrokah! 👋 
Yes, please enable it.

**Comment by erezrokah** [comment]
We've also added an env variable to disable build caching so I can remove it for testing purposes too

**Comment by erezrokah** [comment]
I enabled the feature and removed any env variables

**Comment by janory** [comment]
> I enabled the feature and removed any env variables

Thank you! 👍

**Comment by erezrokah** [comment]
Yey 🎉  A reproduction:
image

Every developer's dream 😄

**Comment by janory** [comment]
@erezrokah we did some changed on our side, can you please help me to trigger the auth request again?

**Comment by erezrokah** [comment]
> @erezrokah we did some changes on our side, can you please help me to trigger the auth request again?

I saw that you pushed a new commit and the build got skipped. Do you want me to add an env variable so you can see that it requires auth?

**Comment by janory** [comment]
> I saw that you pushed a new commit and the build got skipped (that's good!). Do you want me to add an env variable so you can see that it requires auth?

Yes 👍

**Comment by janory** [comment]
@erezrokah it looks like that there is no auth request anymore even with an enabled Git Fork Protection. :)

**Comment by erezrokah** [comment]
I've added an env variable if you'd like to test the other direction (that it requires auth)

**Comment by janory** [comment]
@erezrokah the other direction looks good too:

Screenshot 2023-02-02 at 15 02 43

**Comment by erezrokah** [comment]
> @erezrokah the other direction looks good too:

Nice, I'll close this PR then and you can close the related support ticket I opened. Thanks @janory!

**Comment by janory** [comment]
> > @erezrokah the other direction looks good too:
> 
> Nice, I'll close this PR then and you can close the related support ticket I opened. Thanks @janory!

Cool! 👍 
Thanks for the help with the investigation.

**Pull request closed without merging**
