### PR TITLE
feat(workflows): Reuse `validate-release`

### PR DESCRIPTION
**Pull request by candiduslynx**
This builds on top of ideas from #9668 and can safely replace it.

`wait-for-required-workflows` change is required to make it wait for skipped jobs, too

### CODE REVIEW

**Review by erezrokah — CHANGES_REQUESTED** [review]
Hi @candiduslynx, do you mind testing this from a release PR branch?
You can do it by pushing this commit to a branch name `release-please--branches--main--components-test-workflow` so the validate release workflow will be triggered

**Comment by candiduslynx** [comment]
@erezrokah 
The test is at https://github.com/cloudquery/cloudquery/pull/9736

**Comment by erezrokah** [comment]
> The test is at #9736

Looks like the test failed and we need to update the wait for all workflow to match the nested route `validate-release / Validate release`. See my comment https://github.com/cloudquery/cloudquery/pull/9541#pullrequestreview-1371058249

**Comment by candiduslynx** [comment]
> > The test is at #9736
> 
> Looks like the test failed and we need to update the wait for all workflow to match the nested route `validate-release / Validate release`. See my comment [#9541 (review)](https://github.com/cloudquery/cloudquery/pull/9541#pullrequestreview-1371058249)

I removed custom job name as I think it's what caused the issue. I'll look into it later, too.

**Comment by candiduslynx** [comment]
Closing in favor of #9736 (as it tests the `validate-release`, too)

**Pull request closed without merging**
