### PR TITLE
chore(website): Redirect old plugin docs to hub

### PR DESCRIPTION
**Pull request by yevgenypats**
Part of migration to the cloudquery hub documentation: https://github.com/cloudquery/cloudquery-issues/issues/773

### CODE REVIEW

**Review by erezrokah — COMMENTED** [review]
I don't think this works if you navigate to the plugin internally via the site links as the React App handles the routing.
If you do a hard refresh it works:

https://www.loom.com/share/9dc1bc2b12b7488a9c1ff6c343ad38de?sid=ecdcd801-aa33-4066-963f-3faa502eb38a

**Comment by erezrokah** [comment]
Added a commit mostly generated via:
```
curl https://api.cloudquery.io/plugins | jq -c '.items[] | select( .kind | contains("source")) | {"source":"/docs/plugins/sources/\(.name)/tables/:path*", "destination": "https://hub.cloudquery.io/plugins/source/cloudquery/\(.name)/tables/:path*"}'
curl https://api.cloudquery.io/plugins | jq -c '.items[] | select( .kind | contains("source")) | {"source":"/docs/plugins/sources/\(.name)/:path*", "destination": "https://hub.cloudquery.io/plugins/source/cloudquery/\(.name)"}'
curl https://api.cloudquery.io/plugins | jq -c '.items[] | select( .kind | contains("destination")) | {"source":"/docs/plugins/destinations/\(.name)/:path*", "destination": "https://hub.cloudquery.io/plugins/destination/cloudquery/\(.name)"}'
```

Will push another commit in a bit to fix the docs

**Comment by yevgenypats** [comment]
> Added a commit mostly generated via:
> 
> ```
> curl https://api.cloudquery.io/plugins | jq -c '.items[] | select( .kind | contains("source")) | {"source":"/docs/plugins/sources/\(.name)/tables/:path*", "destination": "https://hub.cloudquery.io/plugins/source/cloudquery/\(.name)/tables/:path*"}'
> curl https://api.cloudquery.io/plugins | jq -c '.items[] | select( .kind | contains("source")) | {"source":"/docs/plugins/sources/\(.name)/:path*", "destination": "https://hub.cloudquery.io/plugins/source/cloudquery/\(.name)"}'
> curl https://api.cloudquery.io/plugins | jq -c '.items[] | select( .kind | contains("destination")) | {"source":"/docs/plugins/destinations/\(.name)/:path*", "destination": "https://hub.cloudquery.io/plugins/destination/cloudquery/\(.name)"}'
> ```
> 
> Will push another commit in a bit to fix the docs

@erezrokah so can I merge this or you want to fix the docs in this PR?

**Comment by yevgenypats** [comment]
> > @erezrokah so can I merge this or you want to fix the docs in this PR?
> 
> This is not ready, I'm moving the plugins docs one by one [148ddd5](https://github.com/cloudquery/cloudquery/commit/148ddd5d50e02e81d7cd3c1d5f97502239b83199).
> 
> Otherwise the Website will still render the olds docs instead of the redirects

Gotcha. okay thanks!

**Comment by erezrokah** [comment]
Bulk of the changes in this PR:

1. Move docs from `website/` under each respective plugin, e.g. from `website/pages/docs/plugins/sources/aws` to `plugins/source/aws/docs`
2. Update publishing workflows to use docs from each respective plugin instead of `website/`
3. Bring back plugin tables docs under `website/pages/docs/plugins/sources/<plugin>/docs/tables`. At the moment we have a single `README.md` file thats links to the Website https://github.com/cloudquery/cloudquery/blob/e3c1f9155f349f0ba8c19b6494e4cfdbaff98ddd/plugins/source/alicloud/docs/tables/README.md?plain=1#L5
Since we'll deprecate the Website tables, this PR brings back the full tables docs to be under the plugins, e.g. https://github.com/cloudquery/cloudquery/tree/89f9c1f5dee5fbb6b652486e83751795eea3c66b/plugins/source/alicloud/docs/tables
4. Add redirects from old docs and tables to the Hub for each relevant plugin https://github.com/cloudquery/cloudquery/blob/89f9c1f5dee5fbb6b652486e83751795eea3c66b/website/vercel.json#L374

## Todo in a follow up

- Clean up https://github.com/cloudquery/cloudquery/tree/89f9c1f5dee5fbb6b652486e83751795eea3c66b/website/tables. The tables there are used in the search box so I didn't not remove them yet

**Pull request merged**
