### PR TITLE
chore: Fix vale linting for buy pages

### PR DESCRIPTION
**Pull request by erezrokah**
#### Summary

Follow up to https://github.com/cloudquery/cloudquery/pull/12219.
The buy pages are autogenerated during build, so they should be `git` ignored. I think https://github.com/cloudquery/cloudquery/pull/12219 removed the ignore by accident.

This PR also changes it so we use the ellipsis icon instead of three dots `...`

### CODE REVIEW

**Comment by erezrokah** [comment]
This should fix the Vale linting errors as see here https://github.com/cloudquery/cloudquery/actions/runs/5570644774/jobs/10174904059?pr=12235

**Comment by yevgenypats** [comment]
Hmm. why we should remove them from git? I feel like auto-generated `tsx` files should be in git as it's easier to debug. also I just added one manual buy page in a previous commit so not sure what to do now (as I didn't need it to be auto-generated)

**Comment by erezrokah** [comment]
> Why we should remove them from git? I feel like auto-generated `tsx` files should be in git as it's easier to debug. also I just added one manual buy page in a previous commit so not sure what to do now (as I didn't need it to be auto-generated).

I'm ok with keeping them too. One sec let met update the PR.

**Comment by erezrokah** [comment]
> Why we should remove them from git? I feel like auto-generated `tsx` files should be in git as it's easier to debug. also I just added one manual buy page in a previous commit so not sure what to do now (as I didn't need it to be auto-generated).

Maybe we should split autogenerated files from manual files, otherwise it hard to trace how those are created, and we might accumulate stale files

**Comment by yevgenypats** [comment]
> > Why we should remove them from git? I feel like auto-generated `tsx` files should be in git as it's easier to debug. also I just added one manual buy page in a previous commit so not sure what to do now (as I didn't need it to be auto-generated).
> 
> Maybe we should split autogenerated files from manual files, otherwise it hard to trace how those are created, and we might accumulate stale files

Im good with splitting, not sure how to do it though :)

**Comment by erezrokah** [comment]
> Im good with splitting, not sure how to do it though :)

Let me take a look into that. Re splitting I removed my changes and ran `npm run prebuild` and got a bunch of new files added (so it's hard to keep autogenerated files in sync with the `git` repo)

**Comment by erezrokah** [comment]
@yevgenypats I updated the PR to:
1. Sync the autogenerated pages with the git repo
2. Use ellipsis icon instead of three dots (related to vale linting)
3. Added missing words to the vale linter and fixed some casing issues we had (see https://github.com/cloudquery/cloudquery/pull/12239/files#diff-401a07a56383945c6471fda443737127a568625437dba85f0de39795979d567b)

I'll take a look into splitting the autogenerated files from the manual ones in another PR, but this PR should be good to fix the CI.

Can you share which file you added manually?

**Review by yevgenypats — APPROVED** [review]

**Pull request merged**
