### PR TITLE
feat(ci): Move `wait-for-required-workflows` logic to a separate file

### PR DESCRIPTION
**Pull request by candiduslynx**
Part of #9929

Inspired by https://github.com/marketplace/actions/github-script#run-a-separate-file-with-an-async-function

The code is moved to a couple of separate js files & steps:
1. Define the required actions
2. Perform actual waiting

Tested #10120

### CODE REVIEW

**Review by erezrokah — CHANGES_REQUESTED** [review]
Hi @candiduslynx, thanks for the PR.

Can we scope this change only to the first task of https://github.com/cloudquery/cloudquery/issues/9929?

That is:
> 1. Move the logic to a separate JavaScript file

That would make it easier to review, and also I think there might be a better way to split the code instead of using 2 action scripts I'd like to discuss, which seems more appropriate in a separate PR, so we don't have to block this one.

**Comment by candiduslynx** [comment]
@erezrokah I reverted the split in b245f74

**Review by erezrokah — COMMENTED** [review]
Thanks @candiduslynx, a few comments:

1. Can we put the new file under a `scripts/workflows/` directory? I think we put all common scripts there
2. Can you confirm the CWD directory when executing the script remains the same? I ask because we do  `fs.readFileSync(file, 'utf8');` on a relative file so I would to ensure that logic doesn't break (we catch any errors when reading files so they won't so up in the logs)

**Comment by candiduslynx** [comment]
@erezrokah 
1. moved file
2. see the run in the test PR: [this line](https://github.com/cloudquery/cloudquery/actions/runs/4714552387/jobs/8360978870?pr=10120#step:4:15) prints CWD to be the root of the repo, as it should be

**Review by erezrokah — APPROVED** [review]

**Pull request merged**
